/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutTrackerIndexRouteImport } from './routes/workout-tracker/index'
import { Route as MusclesIndexRouteImport } from './routes/muscles/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutTrackerIndexRoute = WorkoutTrackerIndexRouteImport.update({
  id: '/workout-tracker/',
  path: '/workout-tracker/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusclesIndexRoute = MusclesIndexRouteImport.update({
  id: '/muscles/',
  path: '/muscles/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/muscles': typeof MusclesIndexRoute
  '/workout-tracker': typeof WorkoutTrackerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/muscles': typeof MusclesIndexRoute
  '/workout-tracker': typeof WorkoutTrackerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/muscles/': typeof MusclesIndexRoute
  '/workout-tracker/': typeof WorkoutTrackerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/muscles' | '/workout-tracker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/muscles' | '/workout-tracker'
  id: '__root__' | '/' | '/muscles/' | '/workout-tracker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MusclesIndexRoute: typeof MusclesIndexRoute
  WorkoutTrackerIndexRoute: typeof WorkoutTrackerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout-tracker/': {
      id: '/workout-tracker/'
      path: '/workout-tracker'
      fullPath: '/workout-tracker'
      preLoaderRoute: typeof WorkoutTrackerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscles/': {
      id: '/muscles/'
      path: '/muscles'
      fullPath: '/muscles'
      preLoaderRoute: typeof MusclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MusclesIndexRoute: MusclesIndexRoute,
  WorkoutTrackerIndexRoute: WorkoutTrackerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
